name: Teste unitário e Lint

on: push

jobs:
  Testando_codigo:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Obter codigo do repositorio dit atual
        uses: actions/checkout@v3

      - name: instalando node
        uses: actions/setup-node@v3

      - name: instala dependencias
        run: npm ci

      - name: Roda eslint
        run: npm run lint


      - name: Roda testes
        run: npm test

      - name: Gera relatotio de testes 
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Jest tests
          path: j*.xml
          reporter: jest-junit

  
